// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTqrcH6pMM_nBAosDy_B2_7gpEt5J1bc',
    appId: '1:552967099990:web:d1dba60705614ef1de8df7',
    messagingSenderId: '552967099990',
    projectId: 'cl-hub-b5634',
    authDomain: 'cl-hub-b5634.firebaseapp.com',
    storageBucket: 'cl-hub-b5634.appspot.com',
    measurementId: 'G-1SQKW3FFP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhv8Z5NTDVAFfZOlnFfVICT2otKVfLx0g',
    appId: '1:552967099990:android:3ac29fa905ec2c60de8df7',
    messagingSenderId: '552967099990',
    projectId: 'cl-hub-b5634',
    storageBucket: 'cl-hub-b5634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs6HODUGPAdDyTlhMSl4xJkym9_LQCk9c',
    appId: '1:552967099990:ios:2803fca15e37e5cfde8df7',
    messagingSenderId: '552967099990',
    projectId: 'cl-hub-b5634',
    storageBucket: 'cl-hub-b5634.appspot.com',
    iosBundleId: 'com.example.clHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs6HODUGPAdDyTlhMSl4xJkym9_LQCk9c',
    appId: '1:552967099990:ios:4e30d6292e84ecb1de8df7',
    messagingSenderId: '552967099990',
    projectId: 'cl-hub-b5634',
    storageBucket: 'cl-hub-b5634.appspot.com',
    iosBundleId: 'com.example.clHub.RunnerTests',
  );
}
